manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: kvepritskiy
      url-base: https://github.com/kvepritskiy
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-dongle-display
      remote: kvepritskiy
      revision: main
      
  self:
    path: config
