CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_USB_DEVICE_STACK=n
CONFIG_BT_DEVICE_NAME="Ergonaut One Left"
CONFIG_BT_DEVICE_NAME_MAX=20
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
