CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_PERIPHERAL=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=nъ
CONFIG_ZMK_USB=n
CONFIG_USB_DEVICE_STACK=n.
CONFIG_BT_DEVICE_NAME="Ergonaut One Left"
